service: portfolio

frameworkVersion: ">=2.12.0 <3.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1


functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /helloworld
          method: get

plugins:
  - serverless-offline